### ISSUE TITLE
Pull Request Overview is blank

### ISSUE THREAD

**Issue by flamtapgt** [sanderaernouts/vsts-git-tasks#11]
Lately, when a pull request is created using this task, the Overview page for the PR comes up completely empty. I suspect an update to ADO would have caused this problem.

**Comment by sanderaernouts** [comment]
@flamtapgt can you add a screenshot or screenshots to this issue? From your description I do not understand what is the problem is.

**Comment by flamtapgt** [comment]
I have observed this once or twice, but when I tried it today, I couldn't reproduce the problem. Will close for now.
