### ISSUE TITLE
Pull request from Release

### ISSUE THREAD

**Issue by JyotsnaMasetti** [sanderaernouts/vsts-git-tasks#3]
Hi,

  Is there any way the i can create a pull request form a Release pipeline.

**Comment by jamers99** [comment]
I peeked at the code and found you can work around it by setting some variables in the Release Pipline.
BUILD_REPOSITORY_NAME = **[your repo's name]**
BUILD_REPOSITORY_PROVIDER = TfsGit

**Comment by JyotsnaMasetti** [comment]
Thank you James, it worked in Release Pipeline. I just tried the same way that I did in Build Pipelines.

**Comment by jamers99** [comment]
See #4

**Comment by jamers99** [comment]
@JyotsnaMasetti but I could.  The variables that are needed are build specific.  **BUILD**_REPOSITORY_NAME and **BUILD**_REPOSITORY_PROVIDER...
